### ISSUE TITLE
How does the main project have so many individual tv episodes?

### ISSUE THREAD

**Issue by su-kkasberg** [Gabisonfire/knightcrawler#14]
I have been scraping for a couple of days. I see a lot of season torrents scraped, but those don’t show up for streaming in my local torrentio. Do I need to enable other scraper sources to fill this gap, or should it be able to play single episodes from a full season torrent?

eztv is failing to pull back results for me. I am not sure if that one of the causes.

`(Use `node --trace-warnings ...` to show where the warning was created)
Scrapping EZTV page 1
(node:1) Warning: Using insecure HTTP parsing
Failed EZTV scrapping for [1] due:  TypeError: Cannot read properties of undefined (reading 'replace')
    at /home/node/app/scrapers/eztv/eztv_api.js:73:42
    at parseTorrent (/home/node/app/scrapers/eztv/eztv_api.js:79:36)
    at Array.map (<anonymous>)
    at parseResults (/home/node/app/scrapers/eztv/eztv_api.js:73:27)
    at /home/node/app/scrapers/eztv/eztv_api.js:52:24
[Sun Jan 28 2024 19:43:46 GMT+0000] finished EZTV scrape`

**Comment by davidjameshowell** [comment]
@su-kkasberg  So it's two things primarily - history and scrapers. 

History since Torrentio (main project) has been running for many years now and has been able to scrape content for all those years, while these new projects require scraping all of the content, including backlogs.

Scrapers because they were able to run eztv and 1337x (along with a massive amount of others that do not exist anymore) that are still being seeded.
